services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ${PWD}/include/minio:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file: .env

  postgres_data:
    image: postgres:15.4-alpine
    volumes:
      - ${PWD}/include/postgres:/var/lib/postgresql/data
    networks:
      - airflow
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jupyter:
    image: jupyter/base-notebook
    restart: 'no'
    ports:
      - 8888:8888
    user: root
    volumes:
      - ./:/home/jovyan/work
    command: ["start.sh", "jupyter", "lab", "--NotebookApp.token=''"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
